### ISSUE TITLE
The tab is a tab and not 2 spaces

### ISSUE THREAD

**Issue by ghost** [ss23/tabs#1]
I tried to use your project in my work environment.
We have a strict rule that indentation should be 2 Spaces.
Your project does not comply with this.

Do you have an estimate of how long it will take to comply?
Troy

**Comment by ss23** [comment]
Please consider using https://github.com/kronicd/spaces instead, but be wary of the perils of GPL. This may affect the licensing of your product.

I would suggest changing to tabs to take advantage of the permissive and truly open BSD license offered by tabs.
